import { Poppins } from "next/font/google";

import "./globals.css";
import styles from "@/app/styles/common.module.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer/page";

const poppins = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className={styles.page}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
